name: notes on web applications
url: http://decasia.github.io
description: "from the humanities IT group at the university of chicago"

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

markdown: kramdown

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
